// Spectrum: The No Hassle Colorpicker
// https://github.com/bgrins/spectrum
// Author: Brian Grinstead
// License: MIT
// Requires: jQuery, spectrum.css
(function(u,e){function Q(d,s){var j=e.extend({},w,d);j.callbacks={move:m(j.move,s),change:m(j.change,s),show:m(j.show,s),hide:m(j.hide,s),beforeShow:m(j.beforeShow,s)};return j}function z(I,s){function j(a){va&&(J.push(tinycolor(a).toHexString()),R&&u.localStorage&&(u.localStorage[R]=J.join(",")))}function i(){var a=[],b=J,c={};if(w){for(var h=0;h<S.length;h++)for(var f=0;f<S[h].length;f++){var r=tinycolor(S[h][f]).toHexString();c[r]=true}for(h=0;h<b.length;h++)r=tinycolor(b[h]).toHexString(),c.hasOwnProperty(r)||
(a.push(b[h]),c[r]=true)}return a.reverse().slice(0,q.maxSelectionSize)}function n(){var a=c(),b=e.map(S,function(b,c){return K(b,a,"sp-palette-row sp-palette-row-"+c)});J&&b.push(K(i(),a,"sp-palette-row sp-palette-row-selection"));ja.html(b.join(""))}function k(){if(z){var a=A,b=c();ka.html(K([a,b],b,"sp-palette-row-initial"))}}function l(){(B===0||L===0||T===0)&&U();o.addClass(la)}function x(){o.removeClass(la)}function C(){var a=tinycolor(y.val());a.ok?b(a,true):y.addClass("sp-validation-error")}
function M(){if(N)U();else if(O.beforeShow(c())!==false){for(var b=0;b<v.length;b++)v[b]&&v[b].hide();N=true;e(V).bind("click.spectrum",a);e(u).bind("resize.spectrum",ma);F.addClass("sp-active");o.show();w&&n();U();g();A=c();k();O.show(A)}}function a(){N&&!m&&(N=false,e(V).unbind("click.spectrum",a),e(u).unbind("resize.spectrum",ma),F.removeClass("sp-active"),o.hide(),tinycolor.equals(c(),A)||(wa?f():b(A,true,true)),O.hide(c()))}function b(a,b,h){if(!tinycolor.equals(a,c())){var r=tinycolor(a),d=
r.toHsv();P=d.h;W=d.s;X=d.v;g();h||(ba=na||r.format);!b&&!tinycolor.equals(a,A)&&f()}}function c(){return tinycolor.fromRatio({h:P,s:W,v:X})}function r(){g();O.move(c())}function g(){y.removeClass("sp-validation-error");h();var a=tinycolor({h:P,s:"1.0",v:"1.0"});Y.css("background-color",a.toHexString());var a=c(),b=a.toHexString();xa.css("background-color",b);oa&&y.val(a.toString(ba));w&&n();k()}function h(){var a=W*L,b=B-X*B,a=Math.max(-D,Math.min(L-D,a-D)),b=Math.max(-D,Math.min(B-D,b-D));pa.css({top:b,
left:a});qa.css({top:P*T-ra})}function f(){var a=c();ca&&E.val(a.toString(ba)).change();A=a;j(a);O.change(a)}function U(){L=Y.width();B=Y.height();D=pa.height();da.width();T=da.height();ra=qa.height();m||o.offset(Z(o,ea));h()}var q=Q(s,I),m=q.flat,t=q.showPaletteOnly,w=q.showPalette||t,z=q.showInitial&&!m,oa=q.showInput,va=q.showSelectionPalette,R=q.localStorageKey,sa=q.theme,O=q.callbacks,ma=fa(U,10),N=false,L=0,B=0,D=0,T=0,ra=0,P=0,W=0,X=0,ga=q.palette.slice(0),S=e.isArray(ga[0])?ga:[ga],J=q.selectionPalette.slice(0),
la="sp-dragging",V=I.ownerDocument,ya=V.body,E=e(I),o=e(p,V).addClass(sa),Y=o.find(".sp-color"),pa=o.find(".sp-dragger"),da=o.find(".sp-hue"),qa=o.find(".sp-slider"),y=o.find(".sp-input"),ja=o.find(".sp-palette"),ka=o.find(".sp-initial"),ta=o.find(".sp-cancel"),ua=o.find(".sp-choose"),ca=E.is("input"),ha=ca&&!m,F=ha?e(G).addClass(sa):e([]),ea=ha?F:E,xa=F.find(".sp-preview"),ia=q.color||ca&&E.val(),A=false,na=q.preferredFormat,ba=na,wa=!q.showButtons;ua.text(q.chooseText);ta.text(q.cancelText);(function(){function c(h){h.data&&
h.data.ignore?(b(e(this).data("color"),true),r()):(b(e(this).data("color")),r(),a());return false}H&&o.find("*:not(input)").attr("unselectable","on");o.toggleClass("sp-flat",m);o.toggleClass("sp-input-disabled",!oa);o.toggleClass("sp-buttons-disabled",!q.showButtons||m);o.toggleClass("sp-palette-disabled",!w);o.toggleClass("sp-palette-only",t);o.toggleClass("sp-initial-disabled",!z);o.addClass(q.className);ha&&E.hide().after(F);m?E.after(o).hide():e(ya).append(o.hide());if(R&&u.localStorage)try{J=
u.localStorage[R].split(",")}catch(h){}ea.bind("click.spectrum touchstart.spectrum",function(b){N?a():M();b.stopPropagation();e(b.target).is("input")||b.preventDefault()});o.click($);y.change(C);y.bind("paste",function(){setTimeout(C,1)});y.keydown(function(a){a.keyCode==13&&C()});ta.bind("click.spectrum",function(b){b.stopPropagation();b.preventDefault();a()});ua.bind("click.spectrum",function(b){b.stopPropagation();b.preventDefault();y.hasClass("sp-validation-error")||(f(),a())});d(da,function(a,
b){P=b/T;r()},l,x);d(Y,function(a,b){W=a/L;X=(B-b)/B;r()},l,x);ia?(b(ia,true),j(ia)):g();m&&M();var i=H?"mousedown.spectrum":"click.spectrum touchstart.spectrum";ja.delegate("span",i,c);ka.delegate("span::nth-child(1)",i,{ignore:true},c)})();var aa={show:M,hide:a,set:function(a){b(a,true)},get:c,destroy:function(){E.show();ea.unbind("click.spectrum touchstart.spectrum");o.remove();F.remove();v[aa.id]=null},container:o};aa.id=v.push(aa)-1;return aa}function Z(d,s){var j=d.outerWidth(),i=d.outerHeight();
s.outerWidth();var n=s.outerHeight(),k=d[0].ownerDocument,l=k.documentElement,m=l.clientWidth+e(k).scrollLeft(),k=l.clientHeight+e(k).scrollTop(),l=s.offset();l.top+=n;l.left-=Math.min(l.left,l.left+j>m&&m>j?Math.abs(l.left+j-m):0);l.top-=Math.min(l.top,l.top+i>k&&k>i?Math.abs(i+n-0):0);return l}function t(){}function $(d){d.stopPropagation()}function m(d,e){var j=Array.prototype.slice,i=j.call(arguments,2);return function(){return d.apply(e,i.concat(j.call(arguments)))}}function d(d,s,j,i){function n(a){a.stopPropagation&&
a.stopPropagation();a.preventDefault&&a.preventDefault();a.returnValue=false}function k(h){if(p){if(c&&!(document.documentMode>=9)&&!h.button)return l();var f=h.originalEvent.touches,g=f?f[0].pageY:h.pageY,f=Math.max(0,Math.min((f?f[0].pageX:h.pageX)-t.left,b)),g=Math.max(0,Math.min(g-t.top,a));r&&n(h);s.apply(d,[f,g])}}function l(){p&&(e(m).unbind(g),e(m.body).removeClass("sp-dragging"),i.apply(d,arguments));p=false}var s=s||function(){},j=j||function(){},i=i||function(){},m=d.ownerDocument||document,
p=false,t={},a=0,b=0,c=e.browser.msie,r="ontouchstart"in u,g={};g.selectstart=n;g.dragstart=n;g[r?"touchmove":"mousemove"]=k;g[r?"touchend":"mouseup"]=l;e(d).bind(r?"touchstart":"mousedown",function(c){if(!(c.which?c.which==3:c.button==2)&&!p&&j.apply(d,arguments)!==false)p=true,a=e(d).height(),b=e(d).width(),t=e(d).offset(),e(m).bind(g),e(m.body).addClass("sp-dragging"),r||k(c),n(c)})}function fa(d,e,j){var i;return function(){var n=this,k=arguments,l=function(){i=null;d.apply(n,k)};j&&clearTimeout(i);
if(j||!i)i=setTimeout(l,e)}}var w={beforeShow:t,move:t,change:t,show:t,hide:t,color:false,flat:false,showInput:false,showButtons:true,showInitial:false,showPalette:false,showPaletteOnly:false,showSelectionPalette:true,localStorageKey:false,maxSelectionSize:7,cancelText:"cancel",chooseText:"choose",preferredFormat:false,className:"",theme:"sp-light",palette:["fff","000"],selectionPalette:[]},v=[],H=e.browser.msie,G="<div class='sp-replacer'><div class='sp-preview'></div><div class='sp-dd'>&#9660;</div></div>",
p=function(){var d="";if(H)for(var e=1;e<=6;e++)d+="<div class='sp-"+e+"'></div>";return["<div class='sp-container'><div class='sp-palette-container'><div class='sp-palette sp-thumb sp-cf'></div></div><div class='sp-picker-container'><div class='sp-top sp-cf'><div class='sp-fill'></div><div class='sp-top-inner'><div class='sp-color'><div class='sp-sat'><div class='sp-val'><div class='sp-dragger'></div></div></div></div><div class='sp-hue'><div class='sp-slider'></div>",d,"</div></div></div><div class='sp-input-container sp-cf'><input class='sp-input' type='text' spellcheck='false'  /></div><div class='sp-initial sp-thumb sp-cf'></div><div class='sp-button-container sp-cf'><a class='sp-cancel' href='#'></a><button class='sp-choose'></button></div></div></div>"].join("")}(),
K=function(d,e,j){for(var i=[],n=0;n<d.length;n++){var k=tinycolor(d[n]),l=k.toHsl().l<0.5?"sp-thumb-dark":"sp-thumb-light";l+=tinycolor.equals(e,d[n])?" sp-thumb-active":"";i.push('<span title="'+k.toHexString()+'" data-color="'+k.toHexString()+'" style="background-color:'+k.toRgbString()+';" class="'+l+'"></span>')}return"<div class='sp-cf "+j+"'>"+i.join("")+"</div>"};e.fn.spectrum=function(d,m){if(typeof d=="string"){if(d=="get")return v[this.eq(0).data("spectrum.id")].get();else if(d=="container")return v[e(this).data("spectrum.id")].container;
return this.each(function(){var j=v[e(this).data("spectrum.id")];j&&(d=="show"&&j.show(),d=="hide"&&j.hide(),d=="set"&&j.set(m),d=="destroy"&&(j.destroy(),e(this).removeData("spectrum.id")))})}return this.spectrum("destroy").each(function(){var j=z(this,d);e(this).data("spectrum.id",j.id)})};e.fn.spectrum.load=true;e.fn.spectrum.loadOpts={};e.fn.spectrum.draggable=d;e.fn.spectrum.processNativeColorInputs=function(){e("<input type='color' />")[0].type==="color"||e("input[type=color]").spectrum({preferredFormat:"hex6"})};
e(function(){e.fn.spectrum.load&&e.fn.spectrum.processNativeColorInputs()})})(this,jQuery);
(function(u){var e,Q,z,Z,t,$,m;function d(a){if(typeof a=="object"&&a.hasOwnProperty("_tc_id"))return a;var a=fa(a),b=a.r,c=a.g,d=a.b,g=x(a.a);return{ok:a.ok,format:a.format,_tc_id:s++,alpha:g,toHsv:function(){var a=H(b,c,d);return{h:a.h,s:a.s,v:a.v,a:g}},toHsvString:function(){var a=H(b,c,d),f=i(a.h*360),e=i(a.s*100),a=i(a.v*100);return g==1?"hsv("+f+", "+e+"%, "+a+"%)":"hsva("+f+", "+e+"%, "+a+"%, "+g+")"},toHsl:function(){var a=w(b,c,d);return{h:a.h,s:a.s,l:a.l,a:g}},toHslString:function(){var a=
w(b,c,d),f=i(a.h*360),e=i(a.s*100),a=i(a.l*100);return g==1?"hsl("+f+", "+e+"%, "+a+"%)":"hsla("+f+", "+e+"%, "+a+"%, "+g+")"},toHex:function(){return G(b,c,d)},toHexString:function(a){return"#"+G(b,c,d,a)},toRgb:function(){return{r:i(b),g:i(c),b:i(d),a:g}},toRgbString:function(){return g==1?"rgb("+i(b)+", "+i(c)+", "+i(d)+")":"rgba("+i(b)+", "+i(c)+", "+i(d)+", "+g+")"},toName:function(){return M[G(b,c,d)]||false},toFilter:function(){var a=G(b,c,d),f=Math.round(x(g)*255).toString(16);return"progid:DXImageTransform.Microsoft.gradient(startColorstr=#"+
f+a+",endColorstr=#"+f+a+")"},toString:function(a){var a=a||this.format,b=false;a==="rgb"&&(b=this.toRgbString());a==="hex"&&(b=this.toHexString());a==="hex6"&&(b=this.toHexString(true));a==="name"&&(b=this.toName());a==="hsl"&&(b=this.toHslString());a==="hsv"&&(b=this.toHsvString());return b||this.toHexString()}}}function fa(a){var b={r:0,g:0,b:0},c=1,d=false,g=false;if(typeof a=="string")a:{var a=a.replace(K,"").replace(I,"").toLowerCase(),h=false;if(C[a])a=C[a],h=true;else if(a=="transparent"){a=
{r:0,g:0,b:0,a:0};break a}var f,a=(f=e.exec(a))?{r:f[1],g:f[2],b:f[3]}:(f=Q.exec(a))?{r:f[1],g:f[2],b:f[3],a:f[4]}:(f=z.exec(a))?{h:f[1],s:f[2],l:f[3]}:(f=Z.exec(a))?{h:f[1],s:f[2],l:f[3],a:f[4]}:(f=t.exec(a))?{h:f[1],s:f[2],v:f[3]}:(f=$.exec(a))?{r:parseInt(f[1],16),g:parseInt(f[2],16),b:parseInt(f[3],16),format:h?"name":"hex"}:(f=m.exec(a))?{r:parseInt(f[1]+""+f[1],16),g:parseInt(f[2]+""+f[2],16),b:parseInt(f[3]+""+f[3],16),format:h?"name":"hex"}:false}if(typeof a=="object"){if(a.hasOwnProperty("r")&&
a.hasOwnProperty("g")&&a.hasOwnProperty("b"))b={r:p(a.r,255)*255,g:p(a.g,255)*255,b:p(a.b,255)*255},d=true,g="rgb";else if(a.hasOwnProperty("h")&&a.hasOwnProperty("s")&&a.hasOwnProperty("v")){var g=a.h,h=a.s,b=a.v,g=p(g,360)*6,h=p(h,100),b=p(b,100),d=j.floor(g),l=g-d,g=b*(1-h);f=b*(1-l*h);h=b*(1-(1-l)*h);d%=6;b={r:[b,f,g,g,h,b][d]*255,g:[h,b,b,f,g,g][d]*255,b:[g,g,h,b,b,f][d]*255};d=true;g="hsv"}else a.hasOwnProperty("h")&&a.hasOwnProperty("s")&&a.hasOwnProperty("l")&&(b=v(a.h,a.s,a.l),d=true,g="hsl");
if(a.hasOwnProperty("a"))c=a.a}b.r=n(255,k(b.r,0));b.g=n(255,k(b.g,0));b.b=n(255,k(b.b,0));if(b.r<1)b.r=i(b.r);if(b.g<1)b.g=i(b.g);if(b.b<1)b.b=i(b.b);return{ok:d,format:a&&a.format||g,r:b.r,g:b.g,b:b.b,a:c}}function w(a,b,c){var a=p(a,255),b=p(b,255),c=p(c,255),d=k(a,b,c),g=n(a,b,c),h,f=(d+g)/2;if(d==g)h=g=0;else{var e=d-g,g=f>0.5?e/(2-d-g):e/(d+g);switch(d){case a:h=(b-c)/e+(b<c?6:0);break;case b:h=(c-a)/e+2;break;case c:h=(a-b)/e+4}h/=6}return{h:h,s:g,l:f}}function v(a,b,c){function d(a,b,c){c<
0&&(c+=1);c>1&&(c-=1);return c<1/6?a+(b-a)*6*c:c<0.5?b:c<2/3?a+(b-a)*(2/3-c)*6:a}a=p(a,360);b=p(b,100);c=p(c,100);if(b==0)c=b=a=c;else var g=c<0.5?c*(1+b):c+b-c*b,e=2*c-g,c=d(e,g,a+1/3),b=d(e,g,a),a=d(e,g,a-1/3);return{r:c*255,g:b*255,b:a*255}}function H(a,b,c){var a=p(a,255),b=p(b,255),c=p(c,255),d=k(a,b,c),e=n(a,b,c),h,f=d-e;if(d==e)h=0;else{switch(d){case a:h=(b-c)/f+(b<c?6:0);break;case b:h=(c-a)/f+2;break;case c:h=(a-b)/f+4}h/=6}return{h:h,s:d==0?0:f/d,v:d}}function G(a,b,c,d){function e(a){return a.length==
1?"0"+a:""+a}a=[e(i(a).toString(16)),e(i(b).toString(16)),e(i(c).toString(16))];return!d&&a[0].charAt(0)==a[0].charAt(1)&&a[1].charAt(0)==a[1].charAt(1)&&a[2].charAt(0)==a[2].charAt(1)?a[0].charAt(0)+a[1].charAt(0)+a[2].charAt(0):a.join("")}function p(a,b){typeof a=="string"&&a.indexOf(".")!=-1&&x(a)===1&&(a="100%");var c=typeof a==="string"&&a.indexOf("%")!=-1,a=n(b,k(0,x(a)));c&&(a*=b/100);if(j.abs(a-b)<1.0E-6)return 1;else if(a>=1)return a%b/x(b);return a}var K=/^[\s,#]+/,I=/\s+$/,s=0,j=Math,i=
j.round,n=j.min,k=j.max,l=j.random,x=u.parseFloat;d.fromRatio=function(a){if(typeof a=="object")for(var b in a)a[b]===1&&(a[b]="1.0");return d(a)};d.equals=function(a,b){return!a||!b?false:d(a).toHex()==d(b).toHex()};d.random=function(){return d.fromRatio({r:l(),g:l(),b:l()})};d.desaturate=function(a,b){var c=d(a).toHsl();c.s-=(b||10)/100;c.s=n(1,k(0,c.s));return d(c)};d.saturate=function(a,b){var c=d(a).toHsl();c.s+=(b||10)/100;c.s=n(1,k(0,c.s));return d(c)};d.greyscale=function(a){return d.desaturate(a,
100)};d.lighten=function(a,b){var c=d(a).toHsl();c.l+=(b||10)/100;c.l=n(1,k(0,c.l));return d(c)};d.darken=function(a,b){var c=d(a).toHsl();c.l-=(b||10)/100;c.l=n(1,k(0,c.l));return d(c)};d.complement=function(a){a=d(a).toHsl();a.h=(a.h+0.5)%1;return d(a)};d.triad=function(a){var b=d(a).toHsl(),c=b.h*360;return[d(a),d({h:(c+120)%360,s:b.s,l:b.l}),d({h:(c+240)%360,s:b.s,l:b.l})]};d.tetrad=function(a){var b=d(a).toHsl(),c=b.h*360;return[d(a),d({h:(c+90)%360,s:b.s,l:b.l}),d({h:(c+180)%360,s:b.s,l:b.l}),
d({h:(c+270)%360,s:b.s,l:b.l})]};d.splitcomplement=function(a){var b=d(a).toHsl(),c=b.h*360;return[d(a),d({h:(c+72)%360,s:b.s,l:b.l}),d({h:(c+216)%360,s:b.s,l:b.l})]};d.analogous=function(a,b,c){var b=b||6,c=c||30,e=d(a).toHsl(),c=360/c,a=[d(a)];e.h*=360;for(e.h=(e.h-(c*b>>1)+720)%360;--b;)e.h=(e.h+c)%360,a.push(d(e));return a};d.monochromatic=function(a,b){for(var b=b||6,c=d(a).toHsv(),e=c.h,g=c.s,c=c.v,h=[],f=1/b;b--;)h.push(d({h:e,s:g,v:c})),c=(c+f)%1;return h};d.readable=function(a,b){var c=d(a).toRgb(),
e=d(b).toRgb();return(e.r-c.r)*(e.r-c.r)+(e.g-c.g)*(e.g-c.g)+(e.b-c.b)*(e.b-c.b)>10404};var C=d.names={aliceblue:"f0f8ff",antiquewhite:"faebd7",aqua:"0ff",aquamarine:"7fffd4",azure:"f0ffff",beige:"f5f5dc",bisque:"ffe4c4",black:"000",blanchedalmond:"ffebcd",blue:"00f",blueviolet:"8a2be2",brown:"a52a2a",burlywood:"deb887",burntsienna:"ea7e5d",cadetblue:"5f9ea0",chartreuse:"7fff00",chocolate:"d2691e",coral:"ff7f50",cornflowerblue:"6495ed",cornsilk:"fff8dc",crimson:"dc143c",cyan:"0ff",darkblue:"00008b",
darkcyan:"008b8b",darkgoldenrod:"b8860b",darkgray:"a9a9a9",darkgreen:"006400",darkgrey:"a9a9a9",darkkhaki:"bdb76b",darkmagenta:"8b008b",darkolivegreen:"556b2f",darkorange:"ff8c00",darkorchid:"9932cc",darkred:"8b0000",darksalmon:"e9967a",darkseagreen:"8fbc8f",darkslateblue:"483d8b",darkslategray:"2f4f4f",darkslategrey:"2f4f4f",darkturquoise:"00ced1",darkviolet:"9400d3",deeppink:"ff1493",deepskyblue:"00bfff",dimgray:"696969",dimgrey:"696969",dodgerblue:"1e90ff",firebrick:"b22222",floralwhite:"fffaf0",
forestgreen:"228b22",fuchsia:"f0f",gainsboro:"dcdcdc",ghostwhite:"f8f8ff",gold:"ffd700",goldenrod:"daa520",gray:"808080",green:"008000",greenyellow:"adff2f",grey:"808080",honeydew:"f0fff0",hotpink:"ff69b4",indianred:"cd5c5c",indigo:"4b0082",ivory:"fffff0",khaki:"f0e68c",lavender:"e6e6fa",lavenderblush:"fff0f5",lawngreen:"7cfc00",lemonchiffon:"fffacd",lightblue:"add8e6",lightcoral:"f08080",lightcyan:"e0ffff",lightgoldenrodyellow:"fafad2",lightgray:"d3d3d3",lightgreen:"90ee90",lightgrey:"d3d3d3",lightpink:"ffb6c1",
lightsalmon:"ffa07a",lightseagreen:"20b2aa",lightskyblue:"87cefa",lightslategray:"789",lightslategrey:"789",lightsteelblue:"b0c4de",lightyellow:"ffffe0",lime:"0f0",limegreen:"32cd32",linen:"faf0e6",magenta:"f0f",maroon:"800000",mediumaquamarine:"66cdaa",mediumblue:"0000cd",mediumorchid:"ba55d3",mediumpurple:"9370db",mediumseagreen:"3cb371",mediumslateblue:"7b68ee",mediumspringgreen:"00fa9a",mediumturquoise:"48d1cc",mediumvioletred:"c71585",midnightblue:"191970",mintcream:"f5fffa",mistyrose:"ffe4e1",
moccasin:"ffe4b5",navajowhite:"ffdead",navy:"000080",oldlace:"fdf5e6",olive:"808000",olivedrab:"6b8e23",orange:"ffa500",orangered:"ff4500",orchid:"da70d6",palegoldenrod:"eee8aa",palegreen:"98fb98",paleturquoise:"afeeee",palevioletred:"db7093",papayawhip:"ffefd5",peachpuff:"ffdab9",peru:"cd853f",pink:"ffc0cb",plum:"dda0dd",powderblue:"b0e0e6",purple:"800080",red:"f00",rosybrown:"bc8f8f",royalblue:"4169e1",saddlebrown:"8b4513",salmon:"fa8072",sandybrown:"f4a460",seagreen:"2e8b57",seashell:"fff5ee",
sienna:"a0522d",silver:"c0c0c0",skyblue:"87ceeb",slateblue:"6a5acd",slategray:"708090",slategrey:"708090",snow:"fffafa",springgreen:"00ff7f",steelblue:"4682b4",tan:"d2b48c",teal:"008080",thistle:"d8bfd8",tomato:"ff6347",turquoise:"40e0d0",violet:"ee82ee",wheat:"f5deb3",white:"fff",whitesmoke:"f5f5f5",yellow:"ff0",yellowgreen:"9acd32"},M=d.hexNames=function(a){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[a[c]]=c);return b}(C);e=RegExp("rgb[\\s|\\(]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))[,|\\s]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))[,|\\s]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))\\s*\\)?");
Q=RegExp("rgba[\\s|\\(]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))[,|\\s]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))[,|\\s]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))[,|\\s]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))\\s*\\)?");z=RegExp("hsl[\\s|\\(]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))[,|\\s]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))[,|\\s]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))\\s*\\)?");Z=RegExp("hsla[\\s|\\(]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))[,|\\s]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))[,|\\s]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))[,|\\s]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))\\s*\\)?");
t=RegExp("hsv[\\s|\\(]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))[,|\\s]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))[,|\\s]+((?:[-\\+]?\\d*\\.\\d+%?)|(?:[-\\+]?\\d+%?))\\s*\\)?");m=/^([0-9a-fA-F]{1})([0-9a-fA-F]{1})([0-9a-fA-F]{1})$/;$=/^([0-9a-fA-F]{2})([0-9a-fA-F]{2})([0-9a-fA-F]{2})$/;u.tinycolor=d})(this);
